Submit Task 6
WendyWang1031/taipei-day-trip pull request #9
Opened 2024-07-03 13:34 UTC by WendyWang1031

王薇婷
http://52.89.39.93:8000/

2024-07-03 16:46 UTC, cwpeng requested changes
Don't show alert dialog with Prime for user.

2024-07-04 00:13 UTC, WendyWang1031 commented
- fix alert dialog with Prime for user .

王薇婷
http://52.89.39.93:8000/

2024-07-04 05:19 UTC, cwpeng requested changes
Homepage reload attraction list infinitely.

2024-07-04 05:36 UTC, WendyWang1031 commented
老師您好，
首頁不斷地重新加載（或刷新）景點列表的意思嗎？
但是我這邊實測+不同電腦+不同瀏覽器+不同人，很像沒有無限加載的情況產生

王薇婷
http://52.89.39.93:8000/
![image](https://github.com/WendyWang1031/taipei-day-trip/assets/152349571/b15180fe-1bc8-4efe-897e-56bba39e56ef)
![截圖 2024-07-04 下午1 36 06](https://github.com/WendyWang1031/taipei-day-trip/assets/152349571/59d361c9-a226-496d-85b1-ac17a2b8b3ee)

2024-07-04 05:56 UTC, WendyWang1031 commented
附上影片連結：
在safari瀏覽器
https://drive.google.com/file/d/1n2yKjV6kEc2GaQGoPqrnf0DRmAYP6RlB/view?usp=sharing

在google chrome無痕模式
https://drive.google.com/file/d/1LvshdkE03b02wXz87nd9LtBNK436M3Md/view?usp=sharing

2024-07-04 09:44 UTC, WendyWang1031 commented
有抓到問題了，先行關閉本次PR～謝謝

2024-07-04 10:54 UTC, WendyWang1031 commented
看樣子是過期Token的問題，的確在寫後端邏輯噴錯誤送到了 500 error
前端response不成功就狂噴回首頁
謝謝老師！很棒的反饋，收穫很多！
王薇婷
http://52.89.39.93:8000/

2024-07-04 17:12 UTC, cwpeng approved these changes
Good. Done.

2024-07-05 01:53 UTC, merged